name: skatemonster
favicon: null
layout_spectrum: 0.24917
typography_spectrum: 0.48775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef4f2'
    - '#fc0011'
    - '#4ec0f2'
    - '#c3ada0'
    - '#745144'
  brandStrength: 0.6808781363070011
  lightness: 0.25397360953502357
  saturation: 0.21747930883429945
  rhythmicContrast: 0.0226316771004349
purpose: []
