name: skatemonster
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#cbc9ca'
    - '#9f9f9f'
    - '#49570c'
    - '#8d770a'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.21747930883429945
  rhythmicContrast: 0.25
purpose: []
